---

# Requires ansible>=2.3.0.

- hosts: miniconda_targets
  vars_files:
    - variables/miniconda-setup.yml
  become: yes

  tasks:
  - name: update all
    yum:
    args:
      name: '*'
      state: latest
      skip_broken: yes

  - name: install prereqs
    yum:
    args:
      name:
        - yum-utils
        - curl
        - wget


  - block:
    - name: find home directory
      shell: "echo ~"
      register: find_home

    - name: check for pre-existing miniconda
      stat:
      register: stat_miniconda
      args:
        path: "{{ find_home.stdout }}/{{ miniconda.path }}"

    - name: download miniconda
      get_url:
      when: stat_miniconda.stat.isdir is not defined
      args:
        url: "{{ miniconda.url_pre }}/{{ miniconda.installer }}"
        dest: "{{ find_home.stdout }}/{{ miniconda.installer }}"
        mode: "{{ miniconda.mode }}"

    - name: install miniconda
      shell: "{{ miniconda.shell}} {{ miniconda.installer }} -b -p {{ find_home.stdout }}/{{ miniconda.path }}"
      when: stat_miniconda.stat.isdir is not defined
      args:
        executable: "{{ miniconda.shell }}"
    become: yes
    become_user: "{{ miniconda.user }}"

...
